### PR TITLE
Fix Travis build

### PR DESCRIPTION
**Pull request by rocboronat**
Right now, Travis' build is failing. This PR will fix it, telling Travis what to do when building the project.

### CODE REVIEW

**Review by EsteveAguilera — APPROVED** [review]
Great job!

**Comment by rocboronat** [comment]
Well, actually, it doesn't build :joy:

**Comment by EsteveAguilera** [comment]
Ouch! 🤦‍♂️ Will try to find some free time next week for this issue...

**Comment by rocboronat** [comment]
Well, as it's running on production... this issue lose lots of priority. The project is probably 100% finished :·D

**Comment by EsteveAguilera** [comment]
Well @rocboronat it seems we're on green now! ;-)

Take a look at the changes and feel free to merge the PR!

**Comment by rocboronat** [comment]
@EsteveAguilera nnnnnnnnice work! 👍

**Pull request merged**
